spring.application.name=ticketing_system_project

# Database configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT ??
# secret : ?? 32??? ??? ??? ?? (HS256 ????? ???? ??)
jwt.secret=v7h6B9p2N5z8eb4fc1d2e3f4g5h6i7j8k9l0m1n2o3p4q5r6s7t8u9v0w1x2y3z4
# Access Token ?? ??: 1?? (3600000ms)
jwt.access-token-expiration=3600000
# Refresh Token ?? ??: 7? (604800000ms)
jwt.refresh-token-expiration=604800000

# Redis ?? ??
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.lettuce.pool.max-active=10
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=2

# ??? ?? ??
# ? ?? ???? ?? ?
queue.activation.batch-size=100
# ??? ?? (???, 10000 = 10?)
queue.activation.interval=10000
# ?? ?? ???? (?, 600 = 10?)
queue.token.active-ttl=600
# ?? ?? ???? (?, 3600 = 1??)
queue.token.waiting-ttl=3600